version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    hostname: namenode
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
    networks:
      - spark
  datanode:
    hostname: datanode
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on:
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
      - 50010:50010
    networks:
      - spark
  spark-master:
    hostname: spark-master
    image: bde2020/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
    networks:
      - spark
  spark-worker:
    hostname: spark-worker
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    depends_on:
      - spark-master
      - namenode
      - datanode
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env
    networks:
      - spark
  spark-notebook:
    hostname: spark-notebook
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    container_name: spark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
    networks:
      - spark
  hue:
    hostname: file-browser
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
    networks:
      - spark

networks:
  spark:
